server:
  port: 8080

spring:
  profiles:
    active: default

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
      concurrency: 3

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    direct:
      exchange: direct_exchange
      queue: direct_queue
      routing-key: direct_routing_key

      topic:
        exchange: topic_exchange
        queue: topic_queue
        routing-key: topic.routing.#

      fanout:
        exchange: fanout_exchange
        queue1: fanout_queue_1
        queue2: fanout_queue_2

      headers:
        exchange: headers_exchange
        queue: headers_queue

kafka:
  replication-factor: 3

  topics:
    raw-scrap-data: raw-scrap-data
    processed-data: processed-data
    db-data: db-data

  consumer-groups:
    raw-scrap-group: raw-scrap-group
    processed-data-group: processed-data-group
    db-data-group: db-data-group

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: INFO