spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: psr-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
    template:
      default-topic: psr-topic

kafka:
  topic: psr-topic
  group-idj: psr-group