spring:
  profiles:
    active: default

  rabbitmq:
    addresses: rabbitmq1,rabbitmq2,rabbitmq3
    host: localhost
    port: 5672
    username: guest
    password: guest

    direct:
      exchange: direct-exchange
      queue: direct-queue
      routing-key: direct-routing-key

retry:
  exceptions:
    - java.util.concurrent.TimeoutException

logging:
  level:
    org.springframework.amqp: DEBUG