spring:
  profiles:
    active: default

  config:
    import:
      - classpath:/application-local-01.yml
      - classpath:/application-local-02.yml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    direct:
      exchange: direct-exchange
      queue: direct-queue
      routing-key: direct-routing-key

    topic:
      exchange: logs-exchange
      error-queue: error-queue
      all-logs-queue: all-logs-queue
      error-routing-key: "*.error.*"
      all-logs-routing-key: "#"

    fanout:
      exchange: fanout-exchange
      queue1: fanout-queue-1
      queue2: fanout-queue-2

    headers:
      exchange: headers-exchange
      queue: headers-queue

logging:
  level:
    org.springframework.amqp: DEBUG