spring:
  profiles:
    active: default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    direct:
      exchange: direct-exchange
      queue: direct-queue
      routing-key: direct-routing-key


logging:
  level:
    org.springframework.amqp: DEBUG