spring:
  profiles:
    active: default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    direct:
      exchange: direct_exchange
      queue: direct_queue
      routing-key: direct_routing_key

    topic:
      exchange: logs_exchange
      error-queue: error_queue
      all-logs-queue: all_logs_queue
      error-routing-key: "*.error.*"
      all-logs-routing-key: "#"

    fanout:
      exchange: fanout_exchange
      queue1: fanout_queue_1
      queue2: fanout_queue_2

    headers:
      exchange: headers_exchange
      queue: headers_queue