services:
  rabbitmq1:
    image: rabbitmq:3.9-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./val/rabbitmq1:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      - rabbitmq_net

  rabbitmq2:
    image: rabbitmq:3.9-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./val/rabbitmq2:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      - rabbitmq_net

  rabbitmq3:
    image: rabbitmq:3.9-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ./val/rabbitmq3:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
