version: '3.8'
services:

  rabbitmq1:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=mysecretcookie
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./val/rabbitmq1:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

  rabbitmq2:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=mysecretcookie
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./val/rabbitmq2:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

  rabbitmq3:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=mysecretcookie
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ./val/rabbitmq3:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
